PetroGastStation.Web/Controllers/PipePriceController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using NPOI.HSSF.UserModel;
using NPOI.SS.UserModel;
using NPOI.XSSF.UserModel;
using PetroGastStation.Web.DataAccess.IDBInterface;
using PetroGastStation.Web.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace PetroGastStation.Web.Controllers
{
    public class PipePriceController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IConfiguration _configuration;
        private readonly IHostingEnvironment Environment;
        private readonly IHostingEnvironment _hostingEnvironment;

        public PipePriceController(IUnitOfWork unitOfWork,
            IConfiguration configuration, IHostingEnvironment _environment, IHostingEnvironment hostingEnvironment)
        {
            _unitOfWork = unitOfWork;
            _configuration = configuration;
            Environment = _environment;
            _hostingEnvironment = hostingEnvironment;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Upload(PipeViewModel formCollection)
        {
            try
            {
                if (formCollection.ImageFile != null)
                {
                    string rpta = "";
                    byte[] buffer;
                    using (MemoryStream ms = new MemoryStream())
                    {
                        formCollection.ImageFile.CopyTo(ms);
                        buffer = ms.ToArray();
                    }
                    List<string> listaanchos = new List<string>();
                    //using (MemoryStream ms = new MemoryStream(buffer))
                    //{
                    //    using (ExcelPackage ep = new ExcelPackage(ms))
                    //    {
                    //        ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
                    //        var ew1 = ep.Workbook.Worksheets["Sheet1"];
                    //        int ncolumnas = ew1.Dimension.End.Column;
                    //        int nfilas = ew1.Dimension.End.Row;
                    //        for (int i = 1; i <= ncolumnas; i++)
                    //        {
                    //            listaanchos.Add((ew1.Column(i).Width * 7).ToString());
                    //        }
                    //    }
                    //}
                }
            }
            catch (Exception)
            {

                throw;
            }
            return View(formCollection);
        }

        //public List<PipeViewModel> readExcel(string FileName)
        //{
        //    try
        //    {
        //        string FilePath = $"{_configuration["FilePath:SecretNormalFilePath"]}{FileName}";
        //        ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
        //        List<PipeViewModel> excelData = new List<PipeViewModel>();
        //        // FileInfo existingFile = new FileInfo(FilePath);

        //        using (var pck = new ExcelPackage())
        //        {
        //            using (var stream = System.IO.File.OpenRead(FilePath))
        //            {
        //                var ws = pck.Workbook.Worksheets["Sheet1"];
        //                var tbl = new DataTable();
        //                var cells = ws.Cells[1, 1, 1, ws.Dimension.End.Column];
        //                for (var i = cells.Start.Column; i <= cells.End.Column; i++)
        //                {
        //                    tbl.Columns.Add(cells[1, i].Value.ToString());
        //                }
        //            }
        //        }


        //        //using (ExcelPackage package = new ExcelPackage(existingFile))
        //        //{
        //        //    ExcelWorksheet worksheet = package.Workbook.Worksheets["Sheet1"];
        //        //    int colCount = worksheet.Dimension.End.Column;  //get Column Count
        //        //    int rowCount = worksheet.Dimension.End.Row;     //get row count
        //        //    foreach (ExcelWorksheet worksheet1 in package.Workbook.Worksheets)
        //        //    {

        //        //    }
        //        //    //int rowCount = worksheet.Dimension.End.Row;
        //        //    for (int row = 1; row <= rowCount; row++)
        //        //    {
        //        //        //string[] getMonthYear = worksheet.Cells[row, 4].Value.ToString().Trim().Split(' ');
        //        //        //excelData.Add(new PipeViewModel()
        //        //        //{
        //        //        //    EnrollmentNo = worksheet.Cells[row, 2].Value.ToString().Trim(),
        //        //        //    Semester = worksheet.Cells[row, 3].Value.ToString().Trim(),
        //        //        //    Month = getMonthYear[0],
        //        //        //    Year = getMonthYear[1],
        //        //        //    StatementNo = worksheet.Cells[row, 5].Value.ToString().Trim()
        //        //        //});
        //        //    }
        //        //}
        //        return excelData;
        //    }
        //    catch (Exception ex)
        //    {
        //        return null;
        //    }
        //}

        //public async Task<IActionResult> OnPostExporttoExcel()
        //{
        //    string webRootPath = _hostingEnvironment.WebRootPath;
        //    string fileName = @"Testingdummy.xlsx";
        //    string URL = string.Format("{0}://{1}/{2}", Request.Scheme, Request.Host, fileName);
        //    FileInfo file = new FileInfo(Path.Combine(webRootPath, fileName));
        //    var memoryStream = new MemoryStream();
        //    // --- Below code would create excel file with dummy data----  
        //    using (var fs = new FileStream(Path.Combine(webRootPath, fileName), FileMode.Create, FileAccess.Write))
        //    {
        //        IWorkbook workbook = new XSSFWorkbook();
        //        ISheet excelSheet = workbook.CreateSheet("Testingdummy");

        //        IRow row = excelSheet.CreateRow(0);
        //        row.CreateCell(0).SetCellValue("CustomerId");
        //        row.CreateCell(1).SetCellValue("FirstName");
        //        row.CreateCell(2).SetCellValue("LastName");
        //        row.CreateCell(3).SetCellValue("Email");

        //        cust = from s in _context.Customers select s;
        //        int counter = 1;
        //        foreach (var customer in cust)
        //        {
        //            string FirstName = string.Empty;
        //            if (customer.FirstName.Length > 100)
        //                FirstName = customer.FirstName.Substring(0, 100);
        //            else
        //                FirstName = customer.FirstName;
        //            row = excelSheet.CreateRow(counter);
        //            row.CreateCell(0).SetCellValue(customer.CustomerId);
        //            row.CreateCell(1).SetCellValue(FirstName);
        //            row.CreateCell(2).SetCellValue(customer.LastName);
        //            row.CreateCell(3).SetCellValue(customer.Email);
        //            counter++;
        //        }
        //        workbook.Write(fs);
        //    }
        //    using (var fileStream = new FileStream(Path.Combine(webRootPath, fileName), FileMode.Open))
        //    {
        //        await fileStream.CopyToAsync(memoryStream);
        //    }
        //    memoryStream.Position = 0;
        //    return File(memoryStream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", fileName);
        //}

        [HttpPost]
        public IActionResult OnPostImportFromExcel()
        {
            IFormFile file = Request.Form.Files[0];
            string folderName = "Upload";
            string webRootPath = _hostingEnvironment.WebRootPath;
            string newPath = Path.Combine(webRootPath, folderName);
            StringBuilder sb = new StringBuilder();
            if (!Directory.Exists(newPath))
                Directory.CreateDirectory(newPath);
            if (file.Length > 0)
            {
                string sFileExtension = Path.GetExtension(file.FileName).ToLower();
                ISheet sheet;
                string fullPath = Path.Combine(newPath, file.FileName);
                using (var stream = new FileStream(fullPath, FileMode.Create))
                {
                    file.CopyTo(stream);
                    stream.Position = 0;
                    if (sFileExtension == ".xls")//This will read the Excel 97-2000 formats    
                    {
                        HSSFWorkbook hssfwb = new HSSFWorkbook(stream);
                        sheet = hssfwb.GetSheetAt(0);
                    }
                    else //This will read 2007 Excel format    
                    {
                        XSSFWorkbook hssfwb = new XSSFWorkbook(stream);
                        sheet = hssfwb.GetSheetAt(0);
                    }
                    IRow headerRow = sheet.GetRow(0);
                    int cellCount = headerRow.LastCellNum;
                    // Start creating the html which would be displayed in tabular format on the screen  
                    sb.Append("<table class='table'><tr>");
                    for (int j = 0; j < cellCount; j++)
                    {
                        NPOI.SS.UserModel.ICell cell = headerRow.GetCell(j);
                        if (cell == null || string.IsNullOrWhiteSpace(cell.ToString())) continue;
                        sb.Append("<th>" + cell.ToString() + "</th>");
                    }
                    sb.Append("</tr>");
                    sb.AppendLine("<tr>");
                    for (int i = (sheet.FirstRowNum + 1); i <= sheet.LastRowNum; i++)
                    {
                        IRow row = sheet.GetRow(i);
                        if (row == null) continue;

PetroGastStation.Web/Views/PipePrice/Index.cshtml
@model PipeViewModel
@{
    ViewData["Title"] = "Index";
}

<h1> Pipe Price </h1>
@*<from asp-action="Upload" asp-controller="PipePrice" method="post" enctype="multipart/form-data">
     <table>  
        <tr>  
            <td>File:</td>  
            <td>  
                <input asp-for="ImageFile" class="form-control" type="file" accept=".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel" style="float: left;text-align: center;border-radius: 60px;" />
            </td>  
        </tr>  
        <tr>  
            <td colspan="2">  
                <input type="submit"  value="Submit"  class="btn btn-outline-primary" />  
            </td>  
        </tr>  
    </table>  
</from>*@
@*@using(Html.BeginForm("Upload", "PipePrice", FormMethod.Post, new {enctype = "multipart/form-data"}))  
{  
  
    <table>  
        <tr>  
            <td>File:</td>  
            <td>  
                <input asp-for="ImageFile" class="form-control" type="file" accept=".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel" style="float: left;text-align: center;border-radius: 60px;" />
            </td>  
        </tr>  
        <tr>  
            <td colspan="2">  
                <input type="submit" name="Submit" value="Submit"  class="btn btn-outline-primary" />  
            </td>  
        </tr>  
    </table>  
}*@ 
<form method="post" enctype="multipart/form-data">      
@* New code to add file Upload and button for importing the data from excel *@  
    <div class="row">  
        <div class="col-md-4">  
            <input type="file" id="fileUpload" name=" fileUpload" class="form-control" />  
        </div>  
        <div class="col-md-8">  
            <input type="button" id="btnUpload" value="Upload File" />  
        </div>  
    </div>  
@*--- Existing code for exporting data to excel----*@  
<div class="row">  
        <div class="col-md-8" style="padding-top:10px;">  
            <button asp-page-handler="ExporttoExcel">Export to Excel</button>  
        </div>  
    </div>  
    <div id="divData"></div>  
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
     <script type="text/javascript">
            $(document).ready(function () {  
    $('#btnUpload').on('click', function () {  
        var fileExtension = ['xls', 'xlsx'];  
        var filename = $('#fileUpload').val();  
//--- Validation for excel file---  
        if (filename.length == 0) {  
            alert("Please select a file.");  
            return false;  
        }  
        else {  
            var extension = filename.replace(/^.*\./, '');  
            if ($.inArray(extension, fileExtension) == -1) {  
                alert("Please select only excel files.");  
                return false;  
            }  
        }  
        var filedata = new FormData();  
        var fileUpload = $("#fileUpload").get(0);  
        var files = fileUpload.files;  
        filedata.append(files[0].name, files[0]);  
        $.ajax({  
            type: "POST",  
            url: "/PipePrice/OnPostImportFromExcel",  
            beforeSend: function (xhr) {  
                xhr.setRequestHeader("XSRF-TOKEN",  
                    $('input:hidden[name="__RequestVerificationToken"]').val());  
            },  
            data: filedata,  
            contentType: false,  
            processData: false,  
            success: function (response) {  
                if (response.length == 0)  
                    alert('Error occurred while uploading the excel file');  
                else {  
                    $('#divData').html(response);  
                }  
            },  
            error: function (e) {  
                $('#divData').html(e.responseText);  
            }  
        });  
    })  
});
    </script>
}